{
  "openapi": "3.0.1",
  "info": {
    "title": "Parcial Final N Capas",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [],
  "paths": {
    "/api/tickets/1": {
      "delete": {
        "summary": "Delete Ticket",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZWNoQGRlbW8uY29tIiwiaWF0IjoxNzUyMDI3MjUwLCJleHAiOjE3NTIwMzA4NTB9.RmPyaVtvTeddSgc59IQ-xP0mDBYF-WhdK1HsS3oezcgUYsLiX5R8vdCtndMpvQNk",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      },
      "get": {
        "summary": "Get Ticket By ID",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "Country",
            "in": "header",
            "description": "",
            "required": false,
            "example": "{{country}}",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZWNoQGRlbW8uY29tIiwiaWF0IjoxNzUyMDI3MDE3LCJleHAiOjE3NTIwMzA2MTd9.sFireXFE4i7skm4IXZbI8i5edJHQOg3O9jJVCgo2z67hfzL9LUzkBl7gWntjxZL3",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "examples": {}
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/tickets": {
      "get": {
        "summary": "Get All Tickets",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "Country",
            "in": "header",
            "description": "",
            "required": false,
            "example": "{{country}}",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "post": {
        "summary": "Save Ticket",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "id",
            "in": "query",
            "description": "",
            "required": true,
            "example": "9",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Country",
            "in": "header",
            "description": "",
            "required": false,
            "example": "{{country}}",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGNvcnJlby5jb20iLCJpYXQiOjE3NTIwMjcwOTMsImV4cCI6MTc1MjAzMDY5M30.Z9SGQxF6sDf_seMArW_GhRQMhhBQadiVI11-3K1gfPenO427TojbAy1QuXDUmsjh",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "titulo": {
                    "type": "string"
                  },
                  "descripcion": {
                    "type": "string"
                  },
                  "correoUsuario": {
                    "type": "string"
                  },
                  "correoSoporte": {
                    "type": "string"
                  }
                },
                "required": [
                  "titulo",
                  "descripcion",
                  "correoUsuario",
                  "correoSoporte"
                ]
              },
              "example": {
                "titulo": "No enciende la impresora",
                "descripcion": "Mi impresora no enciende desde ayer.",
                "correoUsuario": "test@correo.com",
                "correoSoporte": "tech@demo.com"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      },
      "put": {
        "summary": "Update Ticket",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "id",
            "in": "query",
            "description": "",
            "required": true,
            "example": "9",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": false,
            "example": "Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZWNoQGRlbW8uY29tIiwiaWF0IjoxNzUyMDI3MjUwLCJleHAiOjE3NTIwMzA4NTB9.RmPyaVtvTeddSgc59IQ-xP0mDBYF-WhdK1HsS3oezcgUYsLiX5R8vdCtndMpvQNk",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "integer"
                  },
                  "descripcion": {
                    "type": "string"
                  },
                  "estado": {
                    "type": "string"
                  },
                  "correoSoporte": {
                    "type": "string"
                  }
                },
                "required": [
                  "id",
                  "descripcion",
                  "estado",
                  "correoSoporte"
                ]
              },
              "example": {
                "id": 1,
                "descripcion": "Hemos solucionado.",
                "estado": "RESUELTO",
                "correoSoporte": "tech@demo.com"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/auth/register": {
      "post": {
        "summary": "Register User",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "nombre": "Tecnico",
                "correo": "tech@demo.com",
                "password": "123456",
                "nombreRol": "TECH"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/auth/login": {
      "post": {
        "summary": "Login",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "correo": "tech@demo.com",
                "password": "123456"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/users/all": {
      "get": {
        "summary": "Get All Users",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "Country",
            "in": "header",
            "description": "",
            "required": true,
            "example": "{{country}}",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/users/1": {
      "delete": {
        "summary": "Delete User",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "Country",
            "in": "header",
            "description": "",
            "required": false,
            "example": "{{country}}",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/users": {
      "put": {
        "summary": "Update User",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "Country",
            "in": "header",
            "description": "",
            "required": false,
            "example": "{{country}}",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "integer"
                  },
                  "nombre": {
                    "type": "string"
                  },
                  "correo": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  },
                  "nombreRol": {
                    "type": "string"
                  }
                },
                "required": [
                  "id",
                  "nombre",
                  "correo",
                  "password",
                  "nombreRol"
                ]
              },
              "example": {
                "id": 1,
                "nombre": "Luisa Arevalo",
                "correo": "ldarevalo@uca.edu.sv",
                "password": "password123",
                "nombreRol": "USER"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      },
      "post": {
        "summary": "Save User",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "Country",
            "in": "header",
            "description": "",
            "required": false,
            "example": "{{country}}",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "nombre": {
                    "type": "string"
                  },
                  "correo": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  },
                  "nombreRol": {
                    "type": "string"
                  }
                },
                "required": [
                  "nombre",
                  "correo",
                  "password",
                  "nombreRol"
                ]
              },
              "example": {
                "nombre": "David Hurtado",
                "correo": "dhurtado@uca.edu.sv",
                "password": "password456",
                "nombreRol": "TECH"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/users/ldarevalo@uca.edu.sv": {
      "get": {
        "summary": "Get User By Email",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "Country",
            "in": "header",
            "description": "",
            "required": true,
            "example": "{{country}}",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    }
  },
  "components": {
    "schemas": {},
    "securitySchemes": {
      "bearer": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "servers": [],
  "security": []
}